services:
  cavbot2:
    image: cavbot2:latest
    container_name: cavbot2
#    restart: unless-stopped
    environment:
      GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID}
      BEARER: ${BEARER}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      GITHUB_APP_KEY: ${GITHUB_APP_KEY}
      BM_TOKEN: ${BM_TOKEN}
# Codespace and ENV level Secret for BM_TOKEN
      LOG_LEVEL: ${LOG_LEVEL}
      FORUM_DB_DSN: ${FORUM_DB_DSN}
      LOA_NODE_IDS: ${LOA_NODE_IDS}
      SENTRY_DSN: ${SENTRY_DSN}
      APP_ENV: ${APP_ENV}
      PROMO_SWEEP_DISABLED: ${PROMO_SWEEP_DISABLED}
    networks:
      - xenforo_internal

networks:
  xenforo_internal:
    external: true
